blueprint:
  name: Automatic Device Charging Power Off (MQTT)
  description: Monitor power usage on a HA controlled power switch and turn it off
    when usage drops below a designated amount.
  domain: automation
  input:
    power_switch:
      name: Main Power Switch
      description: The power switch to control from the automation.
      selector:
        entity:
          integration: mqtt
          domain:
          - switch
          multiple: false
    power_meter:
      name: Power Usage
      description: The power switch attribute to monitor usage
      selector:
        entity:
          integration: mqtt
          domain:
          - sensor
          device_class:
          - power
          multiple: false
    low_usage_threshold:
      name: Charging Complete Threshold
      description: The amount in watts (W) that the charging is expected to be complete
        at.
      selector:
        number:
          min: 0.0
          max: 15.0
          unit_of_measurement: Watt
          mode: slider
          step: 1.0
    low_usage_hysteresis:
      name: Charging Complete Hysteresis
      description: The time that the charging complete threshold needs to be maintained
        before charging is considered completed.
      selector:
        duration: {}
    post_charge_actions:
      name: Post Charging Actions
      description: Actions to trigger when charging is complete (notifications, etc)
      default: []
      selector:
        action: {}
  source_url: https://github.com/na4ma4/ha-automations/blob/main/blueprints/charger-auto-poweroff-mqtt.yaml
trigger:
- platform: numeric_state
  entity_id: !input power_meter
  below: !input low_usage_threshold
  for: !input low_usage_hysteresis
variables:
  power_switch_entity: ''
condition:
- condition: state
  entity_id: !input power_switch
  state: 'on'
action:
- service: switch.turn_off
  target:
    entity_id: !input power_switch
- choose:
  - conditions: '{{ post_charge_actions is defined }}'
    sequence: !input post_charge_actions
