blueprint:
  name: Alert on Dishwasher Complete
  description: Monitor status on Dishwasher.
  domain: automation
  input:
    dishwasher:
      name: Target Dishwasher State
      description: The dishwasher cycle state to monitor (named MODEL <part> Cycle
        State)
      selector:
        entity:
          filter:
          - integration: ge_home
            domain:
            - sensor
          multiple: false
    cycle_complete_actions:
      name: Cycle Complete Actions
      description: Actions to trigger when cycle is complete
      default: []
      selector:
        action: {}
  source_url: https://github.com/na4ma4/ha-automations/blob/main/blueprints/dishwasher-alert.yaml
trigger:
- trigger: state
  entity_id: !input dishwasher
  from: Rinsing
  to: N/A
- trigger: state
  entity_id: !input dishwasher
  from: Main Wash
  to: N/A
- trigger: state
  entity_id: !input dishwasher
  from: Drying
  to: N/A
action:
  - sequence: !input cycle_complete_actions
