blueprint:
  domain: automation
  name: Z2M - Philips Hue Dimmer Switch (RWL021)
  description: |
    Take the switch fast into use with pre-set configuration.
  source_url: https://github.com/na4ma4/ha-automations/blob/main/blueprints/z2m-blueprint-philips_hue_dimmer_swith_rwl021_fast_setup.yaml
  input:
    zha_device:
      name: Philips Hue Dimmer Switch (RWL021 only)
      description: The switch to be taken into use.
      selector:
        device:
          integration: mqtt
          manufacturer: Philips
          multiple: false
    zha_entity_light:
      name: Light or a light group
      description: Light or a light group to be controlled.
      selector:
        entity:
          multiple: true
          domain: light
mode: queued
max_exceeded: silent
variables:
  device_id: !input zha_device
trigger:
  - platform: device
    domain: mqtt
    device_id: !input zha_device
    type: action
    subtype: on_press
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - service: logbook.log
    data:
      name: Device
      message: "{{ device_id }}"
  - service: logbook.log
    data:
      name: Command
      message: "{{ command }}"
  - service: logbook.log
    data:
      name: device_id
      message: "{{ trigger.event.data.device_id }}"
  - choose:
      - conditions: '{{ command == "on_press" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
              transition: 0.3
            target:
              entity_id: !input zha_entity_light
      - conditions: '{{ command == "off_press" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input zha_entity_light
            data:
              transition: 0.3
      - conditions: '{{ command == "down_hold" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_step_pct: -15
              transition: 0.4
            target:
              entity_id: !input zha_entity_light
      - conditions: '{{ command == "up_hold" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_step_pct: 15
              transition: 0.4
            target:
              entity_id: !input zha_entity_light
      - conditions: '{{ command == "up_short_release" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 70
              transition: 0.3
            target:
              entity_id: !input zha_entity_light
      - conditions: '{{ command == "down_short_release" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 40
              transition: 0.3
            target:
              entity_id: !input zha_entity_light
  - choose:
      - conditions: '{{ command == "on_press" or command == "up_short_release" }}'
        sequence:
          - delay: 0.4
          - service: light.turn_on
            data:
              kelvin: 3400
              transition: 0.5
            target:
              entity_id: !input zha_entity_light
      - conditions: '{{ command == "down_short_release" }}'
        sequence:
          - delay: 0.4
          - service: light.turn_on
            data:
              kelvin: 2300
              transition: 0.5
            target:
              entity_id: !input zha_entity_light
